sudo: required
dist: trusty

language: python

python:
  - "3.5"

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-server-dev-9.4 libjpeg-dev python-enchant

install:
  - if [ ! -e RELEASE-VERSION ]; then echo "v.Travis" > RELEASE-VERSION; fi
  - pip install -e .
  - python setup.py develop
  - cp development.ini.example development.ini
  - python chezbetty/initializedb.py development.ini
  # Latest version pre-install on Travis images 2016-05-03
  - nvm use 4.1.2 && npm install bower && npm install -g bower-installer && bower-installer

script:
  - proutes development.ini
  - prequest development.ini /
  - prequest development.ini /items
  - prequest development.ini /shame
  - prequest development.ini /force_terminal

